/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedSplitsRouteImport } from './routes/_authenticated/splits'
import { Route as AuthenticatedSesionesRouteImport } from './routes/_authenticated/sesiones'
import { Route as AuthenticatedRegistrosRouteImport } from './routes/_authenticated/registros'
import { Route as AuthenticatedPublishingRouteImport } from './routes/_authenticated/publishing'
import { Route as AuthenticatedDistribucionRouteImport } from './routes/_authenticated/distribucion'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedConocimientoRouteImport } from './routes/_authenticated/conocimiento'
import { Route as AuthenticatedConfiguracionRouteImport } from './routes/_authenticated/configuracion'
import { Route as AuthenticatedColaboradoresRouteImport } from './routes/_authenticated/colaboradores'
import { Route as AuthenticatedCatalogoRouteImport } from './routes/_authenticated/catalogo'
import { Route as AuthenticatedAutomatizacionesRouteImport } from './routes/_authenticated/automatizaciones'
import { Route as AuthenticatedAsistenteRouteImport } from './routes/_authenticated/asistente'
import { Route as AuthenticatedActividadRouteImport } from './routes/_authenticated/actividad'
import { Route as AuthenticatedObrasIdRouteImport } from './routes/_authenticated/obras.$id'
import { Route as ApiPublicDawIngestRouteImport } from './routes/api/public/daw.ingest'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSplitsRoute = AuthenticatedSplitsRouteImport.update({
  id: '/splits',
  path: '/splits',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSesionesRoute = AuthenticatedSesionesRouteImport.update({
  id: '/sesiones',
  path: '/sesiones',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRegistrosRoute = AuthenticatedRegistrosRouteImport.update({
  id: '/registros',
  path: '/registros',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPublishingRoute = AuthenticatedPublishingRouteImport.update({
  id: '/publishing',
  path: '/publishing',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDistribucionRoute =
  AuthenticatedDistribucionRouteImport.update({
    id: '/distribucion',
    path: '/distribucion',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedConocimientoRoute =
  AuthenticatedConocimientoRouteImport.update({
    id: '/conocimiento',
    path: '/conocimiento',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedConfiguracionRoute =
  AuthenticatedConfiguracionRouteImport.update({
    id: '/configuracion',
    path: '/configuracion',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedColaboradoresRoute =
  AuthenticatedColaboradoresRouteImport.update({
    id: '/colaboradores',
    path: '/colaboradores',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCatalogoRoute = AuthenticatedCatalogoRouteImport.update({
  id: '/catalogo',
  path: '/catalogo',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAutomatizacionesRoute =
  AuthenticatedAutomatizacionesRouteImport.update({
    id: '/automatizaciones',
    path: '/automatizaciones',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAsistenteRoute = AuthenticatedAsistenteRouteImport.update({
  id: '/asistente',
  path: '/asistente',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedActividadRoute = AuthenticatedActividadRouteImport.update({
  id: '/actividad',
  path: '/actividad',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedObrasIdRoute = AuthenticatedObrasIdRouteImport.update({
  id: '/obras/$id',
  path: '/obras/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicDawIngestRoute = ApiPublicDawIngestRouteImport.update({
  id: '/api/public/daw/ingest',
  path: '/api/public/daw/ingest',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/actividad': typeof AuthenticatedActividadRoute
  '/asistente': typeof AuthenticatedAsistenteRoute
  '/automatizaciones': typeof AuthenticatedAutomatizacionesRoute
  '/catalogo': typeof AuthenticatedCatalogoRoute
  '/colaboradores': typeof AuthenticatedColaboradoresRoute
  '/configuracion': typeof AuthenticatedConfiguracionRoute
  '/conocimiento': typeof AuthenticatedConocimientoRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/distribucion': typeof AuthenticatedDistribucionRoute
  '/publishing': typeof AuthenticatedPublishingRoute
  '/registros': typeof AuthenticatedRegistrosRoute
  '/sesiones': typeof AuthenticatedSesionesRoute
  '/splits': typeof AuthenticatedSplitsRoute
  '/obras/$id': typeof AuthenticatedObrasIdRoute
  '/api/public/daw/ingest': typeof ApiPublicDawIngestRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/actividad': typeof AuthenticatedActividadRoute
  '/asistente': typeof AuthenticatedAsistenteRoute
  '/automatizaciones': typeof AuthenticatedAutomatizacionesRoute
  '/catalogo': typeof AuthenticatedCatalogoRoute
  '/colaboradores': typeof AuthenticatedColaboradoresRoute
  '/configuracion': typeof AuthenticatedConfiguracionRoute
  '/conocimiento': typeof AuthenticatedConocimientoRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/distribucion': typeof AuthenticatedDistribucionRoute
  '/publishing': typeof AuthenticatedPublishingRoute
  '/registros': typeof AuthenticatedRegistrosRoute
  '/sesiones': typeof AuthenticatedSesionesRoute
  '/splits': typeof AuthenticatedSplitsRoute
  '/obras/$id': typeof AuthenticatedObrasIdRoute
  '/api/public/daw/ingest': typeof ApiPublicDawIngestRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/actividad': typeof AuthenticatedActividadRoute
  '/_authenticated/asistente': typeof AuthenticatedAsistenteRoute
  '/_authenticated/automatizaciones': typeof AuthenticatedAutomatizacionesRoute
  '/_authenticated/catalogo': typeof AuthenticatedCatalogoRoute
  '/_authenticated/colaboradores': typeof AuthenticatedColaboradoresRoute
  '/_authenticated/configuracion': typeof AuthenticatedConfiguracionRoute
  '/_authenticated/conocimiento': typeof AuthenticatedConocimientoRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/distribucion': typeof AuthenticatedDistribucionRoute
  '/_authenticated/publishing': typeof AuthenticatedPublishingRoute
  '/_authenticated/registros': typeof AuthenticatedRegistrosRoute
  '/_authenticated/sesiones': typeof AuthenticatedSesionesRoute
  '/_authenticated/splits': typeof AuthenticatedSplitsRoute
  '/_authenticated/obras/$id': typeof AuthenticatedObrasIdRoute
  '/api/public/daw/ingest': typeof ApiPublicDawIngestRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/sitemap.xml'
    | '/actividad'
    | '/asistente'
    | '/automatizaciones'
    | '/catalogo'
    | '/colaboradores'
    | '/configuracion'
    | '/conocimiento'
    | '/dashboard'
    | '/distribucion'
    | '/publishing'
    | '/registros'
    | '/sesiones'
    | '/splits'
    | '/obras/$id'
    | '/api/public/daw/ingest'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/sitemap.xml'
    | '/actividad'
    | '/asistente'
    | '/automatizaciones'
    | '/catalogo'
    | '/colaboradores'
    | '/configuracion'
    | '/conocimiento'
    | '/dashboard'
    | '/distribucion'
    | '/publishing'
    | '/registros'
    | '/sesiones'
    | '/splits'
    | '/obras/$id'
    | '/api/public/daw/ingest'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/sitemap.xml'
    | '/_authenticated/actividad'
    | '/_authenticated/asistente'
    | '/_authenticated/automatizaciones'
    | '/_authenticated/catalogo'
    | '/_authenticated/colaboradores'
    | '/_authenticated/configuracion'
    | '/_authenticated/conocimiento'
    | '/_authenticated/dashboard'
    | '/_authenticated/distribucion'
    | '/_authenticated/publishing'
    | '/_authenticated/registros'
    | '/_authenticated/sesiones'
    | '/_authenticated/splits'
    | '/_authenticated/obras/$id'
    | '/api/public/daw/ingest'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiPublicDawIngestRoute: typeof ApiPublicDawIngestRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/splits': {
      id: '/_authenticated/splits'
      path: '/splits'
      fullPath: '/splits'
      preLoaderRoute: typeof AuthenticatedSplitsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sesiones': {
      id: '/_authenticated/sesiones'
      path: '/sesiones'
      fullPath: '/sesiones'
      preLoaderRoute: typeof AuthenticatedSesionesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/registros': {
      id: '/_authenticated/registros'
      path: '/registros'
      fullPath: '/registros'
      preLoaderRoute: typeof AuthenticatedRegistrosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/publishing': {
      id: '/_authenticated/publishing'
      path: '/publishing'
      fullPath: '/publishing'
      preLoaderRoute: typeof AuthenticatedPublishingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/distribucion': {
      id: '/_authenticated/distribucion'
      path: '/distribucion'
      fullPath: '/distribucion'
      preLoaderRoute: typeof AuthenticatedDistribucionRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/conocimiento': {
      id: '/_authenticated/conocimiento'
      path: '/conocimiento'
      fullPath: '/conocimiento'
      preLoaderRoute: typeof AuthenticatedConocimientoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/configuracion': {
      id: '/_authenticated/configuracion'
      path: '/configuracion'
      fullPath: '/configuracion'
      preLoaderRoute: typeof AuthenticatedConfiguracionRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/colaboradores': {
      id: '/_authenticated/colaboradores'
      path: '/colaboradores'
      fullPath: '/colaboradores'
      preLoaderRoute: typeof AuthenticatedColaboradoresRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/catalogo': {
      id: '/_authenticated/catalogo'
      path: '/catalogo'
      fullPath: '/catalogo'
      preLoaderRoute: typeof AuthenticatedCatalogoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/automatizaciones': {
      id: '/_authenticated/automatizaciones'
      path: '/automatizaciones'
      fullPath: '/automatizaciones'
      preLoaderRoute: typeof AuthenticatedAutomatizacionesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/asistente': {
      id: '/_authenticated/asistente'
      path: '/asistente'
      fullPath: '/asistente'
      preLoaderRoute: typeof AuthenticatedAsistenteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/actividad': {
      id: '/_authenticated/actividad'
      path: '/actividad'
      fullPath: '/actividad'
      preLoaderRoute: typeof AuthenticatedActividadRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/obras/$id': {
      id: '/_authenticated/obras/$id'
      path: '/obras/$id'
      fullPath: '/obras/$id'
      preLoaderRoute: typeof AuthenticatedObrasIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/daw/ingest': {
      id: '/api/public/daw/ingest'
      path: '/api/public/daw/ingest'
      fullPath: '/api/public/daw/ingest'
      preLoaderRoute: typeof ApiPublicDawIngestRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedActividadRoute: typeof AuthenticatedActividadRoute
  AuthenticatedAsistenteRoute: typeof AuthenticatedAsistenteRoute
  AuthenticatedAutomatizacionesRoute: typeof AuthenticatedAutomatizacionesRoute
  AuthenticatedCatalogoRoute: typeof AuthenticatedCatalogoRoute
  AuthenticatedColaboradoresRoute: typeof AuthenticatedColaboradoresRoute
  AuthenticatedConfiguracionRoute: typeof AuthenticatedConfiguracionRoute
  AuthenticatedConocimientoRoute: typeof AuthenticatedConocimientoRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDistribucionRoute: typeof AuthenticatedDistribucionRoute
  AuthenticatedPublishingRoute: typeof AuthenticatedPublishingRoute
  AuthenticatedRegistrosRoute: typeof AuthenticatedRegistrosRoute
  AuthenticatedSesionesRoute: typeof AuthenticatedSesionesRoute
  AuthenticatedSplitsRoute: typeof AuthenticatedSplitsRoute
  AuthenticatedObrasIdRoute: typeof AuthenticatedObrasIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedActividadRoute: AuthenticatedActividadRoute,
  AuthenticatedAsistenteRoute: AuthenticatedAsistenteRoute,
  AuthenticatedAutomatizacionesRoute: AuthenticatedAutomatizacionesRoute,
  AuthenticatedCatalogoRoute: AuthenticatedCatalogoRoute,
  AuthenticatedColaboradoresRoute: AuthenticatedColaboradoresRoute,
  AuthenticatedConfiguracionRoute: AuthenticatedConfiguracionRoute,
  AuthenticatedConocimientoRoute: AuthenticatedConocimientoRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDistribucionRoute: AuthenticatedDistribucionRoute,
  AuthenticatedPublishingRoute: AuthenticatedPublishingRoute,
  AuthenticatedRegistrosRoute: AuthenticatedRegistrosRoute,
  AuthenticatedSesionesRoute: AuthenticatedSesionesRoute,
  AuthenticatedSplitsRoute: AuthenticatedSplitsRoute,
  AuthenticatedObrasIdRoute: AuthenticatedObrasIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiPublicDawIngestRoute: ApiPublicDawIngestRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
